### ISSUE TITLE
Add a better description to README and remove unused text

### ISSUE THREAD

**Issue by kammradt** [Esquenta-Porquinho/documentation#3]
### What ?

We need to create a better description to explain how the project works, a good image with the process would help a lot.

---  

### How you'd like ?

A new section should be added with a title like 'How it works', and it **must** follow the same style as the rest of the README

---  

### Describe alternatives you've considered

Just copy one section and change what do you need.
To create the image you can use something like [Canva](https://www.canva.com/) or another tool to create graphs

---  

### Additional context

Se fizer algo errado vai apanha

---

**Comment by JJMoraes** [comment]
Two images were added explaining the purpose and communication of the project. The unused texts and links were removed and a folder created for the images to be used.

Link PR --> https://github.com/Esquenta-Porquinho/documentation/pull/4

**Comment by kammradt** [comment]
I verified the PR that you created and approved. Thanks!
